### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by desireBanse** [leafney/alpine-mariadb#3]
Sending build context to Docker daemon  75.26kB
Step 1/9 : FROM alpine:3.9
3.9: Pulling from library/alpine
e7c96db7181b: Already exists 
Digest: sha256:769fddc7cc2f0a1c35abb2f91432e8beecf83916c421420e6a6da9f8975464b6
Status: Downloaded newer image for alpine:3.9
 ---> 055936d39205
Step 2/9 : MAINTAINER leafney "babycoolzx@126.com"
 ---> Running in 60ebcab0d55a
Removing intermediate container 60ebcab0d55a
 ---> de55bdb38987
Step 3/9 : ENV MYSQL_VERSION=10.3.13-r0
 ---> Running in ff5e8271ef38
Removing intermediate container ff5e8271ef38
 ---> a2315dfe9f41
Step 4/9 : RUN apk add --no-cache mysql=${MYSQL_VERSION} mysql-client=${MYSQL_VERSION} mariadb-server-utils=${MYSQL_VERSION} && 	addgroup mysql mysql && 	mkdir /scripts && 	rm -rf /var/cache/apk/*
 ---> Running in 256d428282cb
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  mariadb-server-utils-10.3.15-r0:
    breaks: world[mariadb-server-utils=10.3.13-r0]
  mysql-10.3.15-r0:
    breaks: world[mysql=10.3.13-r0]
  mysql-client-10.3.15-r0:
    breaks: world[mysql-client=10.3.13-r0]
The command '/bin/sh -c apk add --no-cache mysql=${MYSQL_VERSION} mysql-client=${MYSQL_VERSION} mariadb-server-utils=${MYSQL_VERSION} && 	addgroup mysql mysql && 	mkdir /scripts && 	rm -rf /var/cache/apk/*' returned a non-zero code: 3

**Comment by leafney** [comment]
The reason for the error is that the version of MySQL has been upgraded to version `10.3.15-r0` on alpine 3.9,you can change the `ENV MYSQL_VERSION=10.3.13-r0` by yourself and then to rebuild it or get my docker with tag `leafney/alpine-mariadb:10.3.13` .
After that, I will upgrade the relevant containers to the latest version.

**Comment by leafney** [comment]
Ok, Upgrade.
